---
- name: Enable Chrony
  hosts: all
  tasks:
  - name: Enable Chrony | Install packages
    package:
      state: present
      name: "{{ item }}"
    with_items:
      - chrony

  - name: Enable Chrony | Disable ntpd service
    service:
      name: ntpd
      state: stopped
      enabled: no

  - name: Enable Chrone | Enable chronyd service
    service:
      name: chronyd
      state: started
      enabled: yes
